# Generated by Django 5.2.5 on 2025-09-01 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='case_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['case'], name='evidence_case_idx'),
        ),
    ]
