version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: criminal
      POSTGRES_USER: criminal
      POSTGRES_PASSWORD: criminal
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U criminal"]
      interval: 5s
      timeout: 3s
      retries: 5
  web:
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: criminal
      POSTGRES_USER: criminal
      POSTGRES_PASSWORD: criminal
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: dev-key
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata:
